
package br.com.soc.test.ws.servico;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ListagemExamesService", targetNamespace = "http://servico.ws.test.soc.com.br/", wsdlLocation = "http://localhost:8080/SOCTest/ws/exames?wsdl")
public class ListagemExamesService
    extends Service
{

    private final static URL LISTAGEMEXAMESSERVICE_WSDL_LOCATION;
    private final static WebServiceException LISTAGEMEXAMESSERVICE_EXCEPTION;
    private final static QName LISTAGEMEXAMESSERVICE_QNAME = new QName("http://servico.ws.test.soc.com.br/", "ListagemExamesService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/SOCTest/ws/exames?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LISTAGEMEXAMESSERVICE_WSDL_LOCATION = url;
        LISTAGEMEXAMESSERVICE_EXCEPTION = e;
    }

    public ListagemExamesService() {
        super(__getWsdlLocation(), LISTAGEMEXAMESSERVICE_QNAME);
    }

    public ListagemExamesService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LISTAGEMEXAMESSERVICE_QNAME, features);
    }

    public ListagemExamesService(URL wsdlLocation) {
        super(wsdlLocation, LISTAGEMEXAMESSERVICE_QNAME);
    }

    public ListagemExamesService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LISTAGEMEXAMESSERVICE_QNAME, features);
    }

    public ListagemExamesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ListagemExamesService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ListagemExames
     */
    @WebEndpoint(name = "ListagemExamesPort")
    public ListagemExames getListagemExamesPort() {
        return super.getPort(new QName("http://servico.ws.test.soc.com.br/", "ListagemExamesPort"), ListagemExames.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ListagemExames
     */
    @WebEndpoint(name = "ListagemExamesPort")
    public ListagemExames getListagemExamesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servico.ws.test.soc.com.br/", "ListagemExamesPort"), ListagemExames.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LISTAGEMEXAMESSERVICE_EXCEPTION!= null) {
            throw LISTAGEMEXAMESSERVICE_EXCEPTION;
        }
        return LISTAGEMEXAMESSERVICE_WSDL_LOCATION;
    }

}
